name: Fetch and Push DDR News

on:
  schedule:
    - cron: "0 */1 * * *"  # Runs every 6 hours
  workflow_dispatch:  # 👈 Allows manual triggering

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        
      - name: Scrape News and Push to Backend
        env:
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
          BACKEND_API_URL_HASHES: ${{ secrets.BACKEND_API_URL_HASHES }}
          API_KEY: ${{ secrets.API_KEY }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: node scrapeNews.js
