name: Fetch and Push DDR News

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # 👈 Allows manual triggering

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Set up Google API credentials
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "$GOOGLE_API_KEY" > google-api.json
          echo "Google API credentials set up."

      - name: Scrape News and Push to Backend
        env:
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
          BACKEND_API_URL_HASHES: ${{ secrets.BACKEND_API_URL_HASHES }}
          API_KEY: ${{ secrets.API_KEY }}
        run: node scrapeNews.js
